name: desmos2python
channels:
  - conda-forge
  - python
  - defaults
dependencies:
  - python=3.8
  - pip
  - flake8
  - setuptools
  - wheel
  - numpy
  - matplotlib
  - PyQt5
  - sympy
  - antlr4-python3-runtime==4.10
  - jinja2
