#!/bin/bash

# use jinja2-cli to render an up-to-date `repo_helper.yaml` config file.

set -e

script_dir=$(dirname "$0")
repo_dir=$(realpath "${script_dir}/..")

version=$(python -m setuptools_scm)
git tag "v${version}"

rendered_string=$(jinja2 $repo_dir/_config_templates/repo_helper.jinja2 -D version=$version)

output_filepath="${repo_dir}/repo_helper.yml"

echo -e "${rendered_string}" > $output_filepath
echo -e "saved rendered templated to:\n\t${output_filepath}"
